services:
  app:
    build:
      context: .
      args:
        IMAGE: ghcr.io/nationalarchives/tna-python-root
        IMAGE_TAG: preview
    environment:
      - RUNTIME=develop
      - ENVIRONMENT_NAME=develop
      - CONFIG=config.Develop
      - DEBUG=true
      - SECRET_KEY=abc123
      - NPM_DEVELOP_COMMAND=dev
      - COOKIE_DOMAIN=localhost
      - CSP_STYLE_SRC='self',fonts.googleapis.com,p.typekit.net,use.typekit.net
      - CSP_FONT_SRC='self',fonts.gstatic.com,use.typekit.net
      - UPTIME_KUMA_API_URL=https://uptime.tna.dblclk.dev/api
      - UPTIME_KUMA_STATUS_PAGE_SLUG=nationalarchives
    ports:
      - 65516:8080
    volumes:
      - ./:/app

  dev:
    environment:
      - CONFIG=config.Test
    image: ghcr.io/nationalarchives/tna-python-dev:preview
    volumes:
      - ./:/app

  docs:
    image: squidfunk/mkdocs-material
    volumes:
      - .:/docs
    ports:
      - 65515:8000
